import { StyleSheet } from "react-native";
const styles = StyleSheet.create({
    container:{
        marginTop:30,
        paddingLeft:30,
        paddingRight:30,
        paddingTop:20,
        backgroundColor:"#171717",
        flex:1,
        flexDirection:"column"
    },
    header:{
        marginTop:26,
        flexDirection:"row",
        justifyContent:"space-between",
    },
    textH:{ 
        fontSize:18,
        fontWeight:"500",
        color:"white"
    },
    iconH:{
        marginTop:10
    },
    avatar:{  
        marginTop:20,  
        flexDirection:"row",
        height:150,
        width:150,
        borderRadius:75,
        backgroundColor:"red",
        alignSelf:"center"
    },
    nameU:{
        marginTop:10,
        fontSize:30,
        fontWeight:"500",
        color:"white",
        alignSelf:"center"
    },
    statusContainer:{
        width:370,
        height:60,
        borderRadius:20,
        marginTop:30,
        backgroundColor:"#353535",
        alignSelf:"center",
       
    },
    statusContent:{
        flexDirection:"row",
        justifyContent:"space-between"
    },
    covStatText:{
        marginLeft:20,
        color:"white",
        fontSize:24,
        fontWeight:"400",
        // alignItems:"center",
        marginTop:12
    },
    statIndicator:{
        marginRight:20,
        marginTop:15
    },
    vacNameContainer:{
        width:370,
        height:60,
        borderRadius:20,
        marginTop:15,
        backgroundColor:"#353535",
        alignSelf:"center",
    },
    vacNameContent:{
        flexDirection:"row",
        justifyContent:"center"

    },
    vacName:{
        color:"white",
        fontSize:24,
        fontWeight:"400",
        marginTop:12,
        alignSelf:"center"
    },
    vacContainer:{
        width:370,
        flexDirection:"row", 
        justifyContent:"space-between",
        alignSelf:"center"
    },
    vacBox1:{
        
        height:90,
        width:115,
        borderRadius:20,
        backgroundColor:"#353535",
        marginTop:15,
        flexDirection:"column",
        alignItems:"center"
    },
    vacBox2:{
        
        height:90,
        width:115,
        borderRadius:20,
        backgroundColor:"#353535",
        marginTop:15,
        alignItems:"center",
        flexDirection:"column"
    },
    vacBox3:{
        height:90,
        width:115,
        borderRadius:20,
        backgroundColor:"#353535",
        marginTop:15,
        alignItems:"center",
        flexDirection:"column",
        borderWidth:1,
        borderColor:"red"
    },
    vacIndicator:{
        
        marginTop:18,
        alignSelf:"center"

    },
    vacDose:{
        marginTop:8,
        color:"white",
        fontSize:16,
        fontWeight:"400"
    },
    updVacButton:{
        marginTop:15,
        width:370,
        height:50,
        backgroundColor:"black",
        borderRadius:5,
        alignSelf:"center"
    },
    vacStatChange:{
        marginTop:8,
        color:"white",
        fontSize:24,
        fontWeight:"400",
        alignSelf:"center"
    }

});
export default styles;